# Generated by Django 2.0 on 2018-01-05 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='ip地址')),
                ('org', models.CharField(choices=[('YJH', '优计划'), ('TBS', '淘巴士')], max_length=5, verbose_name='所在组织')),
                ('provider', models.CharField(max_length=50, verbose_name='服务商')),
                ('platform', models.CharField(max_length=50, verbose_name='平台')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='服务')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('version', models.CharField(max_length=20, verbose_name='版本')),
                ('host', models.ManyToManyField(to='server.Host', verbose_name='所属服务器')),
            ],
        ),
    ]
