# Generated by Django 2.0 on 2018-02-23 06:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='ip地址')),
                ('desc', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('region', models.CharField(default='华南', max_length=10, verbose_name='所在可用区')),
                ('provider', models.CharField(default='阿里云', max_length=50, verbose_name='服务商')),
                ('platform', models.CharField(default='Linux', max_length=50, verbose_name='平台')),
                ('pay_method', models.CharField(choices=[('reserved', '包年包月'), ('on_demand', '按量付费')], default='reserved', max_length=10, verbose_name='付费方式')),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='到期时间')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='年费')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止')], default='running', max_length=10, verbose_name='运行状态')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '主机',
                'verbose_name': '主机',
            },
        ),
        migrations.CreateModel(
            name='HostHardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30, unique=True, verbose_name='实例规格')),
                ('specific', models.CharField(max_length=20, verbose_name='规格族')),
                ('cpu', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='最小为1')], verbose_name='处理器')),
                ('memory', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='最小为1')], verbose_name='内存')),
            ],
            options={
                'verbose_name_plural': '配置',
                'verbose_name': '配置',
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='组织名称')),
                ('code', models.CharField(max_length=10, verbose_name='组织代码')),
                ('desc', models.CharField(blank='True', max_length=100, verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '组织',
                'verbose_name': '组织',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='服务')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('version', models.CharField(max_length=20, verbose_name='版本')),
                ('host', models.ManyToManyField(to='server.Host', verbose_name='所属服务器')),
            ],
            options={
                'verbose_name_plural': '服务',
                'verbose_name': '服务',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='hardware',
            field=models.ForeignKey(default=1, on_delete='PROTECT', to='server.HostHardware', verbose_name='硬件配置'),
        ),
        migrations.AddField(
            model_name='host',
            name='org',
            field=models.ForeignKey(on_delete='PROTECT', to='server.Org', verbose_name='所在组织'),
        ),
    ]
