# Generated by Django 2.0 on 2018-01-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='platform',
            field=models.CharField(default='Linux', max_length=50, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='host',
            name='provider',
            field=models.CharField(default='阿里云', max_length=50, verbose_name='服务商'),
        ),
    ]
