# Generated by Django 2.0 on 2018-01-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180105_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='hardware',
            field=models.CharField(default='', max_length=200, verbose_name='硬件配置'),
        ),
        migrations.AlterField(
            model_name='host',
            name='org',
            field=models.CharField(choices=[('YJH', '优计划'), ('TBS', '淘巴士'), ('CST', '商家')], max_length=5, verbose_name='所在组织'),
        ),
    ]
