# Generated by Django 2.0 on 2018-03-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_host_instance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='instance_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='实例id'),
        ),
    ]
