# Generated by Django 2.0 on 2018-01-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20180105_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hardware',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='硬件配置'),
        ),
    ]
