# Generated by Django 2.0 on 2018-01-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20180105_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.CharField(default='running', max_length=10, verbose_name='运行状态'),
        ),
    ]
