# Generated by Django 2.0 on 2018-01-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_host_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='desc',
            field=models.CharField(default='', max_length=200, verbose_name='描述'),
        ),
    ]
