# Generated by Django 2.0 on 2018-01-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20180111_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='组织名称')),
                ('code', models.CharField(max_length=10, verbose_name='组织代码')),
                ('desc', models.CharField(max_length=100, verbose_name='描述')),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='描述'),
        ),
    ]
