# Generated by Django 2.0 on 2018-01-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20180112_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='org',
            field=models.ForeignKey(on_delete='PROTECT', to='server.Org', verbose_name='所在组织'),
        ),
        migrations.AlterField(
            model_name='org',
            name='desc',
            field=models.CharField(blank='True', max_length=100, verbose_name='描述'),
        ),
    ]
