# Generated by Django 2.0 on 2018-01-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20180112_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='org',
            field=models.ForeignKey(on_delete='PROTECT', to='server.Org', verbose_name='所在组织'),
        ),
    ]
