# Generated by Django 2.0 on 2018-01-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20180112_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostHardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='实例规格')),
                ('cpu', models.IntegerField(max_length=2, verbose_name='处理器')),
                ('memory', models.IntegerField(max_length=5, verbose_name='内存')),
                ('disk', models.IntegerField(max_length=5, verbose_name='磁盘')),
            ],
            options={
                'verbose_name_plural': '配置',
                'verbose_name': '配置',
            },
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '主机', 'verbose_name_plural': '主机'},
        ),
        migrations.AlterModelOptions(
            name='org',
            options={'verbose_name': '组织', 'verbose_name_plural': '组织'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '服务', 'verbose_name_plural': '服务'},
        ),
    ]
