# Generated by Django 2.0 on 2018-01-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20180113_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosthardware',
            name='disk',
        ),

        migrations.AlterField(
            model_name='hosthardware',
            name='cpu',
            field=models.IntegerField(verbose_name='处理器'),
        ),
        migrations.AlterField(
            model_name='hosthardware',
            name='memory',
            field=models.IntegerField(verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='hosthardware',
            name='version',
            field=models.CharField(max_length=30, verbose_name='实例规格'),
        ),
    ]
