# Generated by Django 2.0 on 2018-01-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20180113_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hardware',
            field=models.ForeignKey(on_delete='PROTECT', to='server.HostHardware', verbose_name='硬件配置'),
        ),
    ]
