# Generated by Django 2.0 on 2018-01-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20180113_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hardware',
            field=models.ForeignKey(default=1, on_delete='PROTECT', to='server.HostHardware', verbose_name='硬件配置'),
        ),
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='组织名称'),
        ),
    ]
