# Generated by Django 2.0 on 2018-01-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20180115_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosthardware',
            name='version',
            field=models.CharField(max_length=30, unique=True, verbose_name='实例规格'),
        ),
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(max_length=20, verbose_name='组织名称'),
        ),
    ]
