# Generated by Django 2.0 on 2018-01-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_auto_20180115_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosthardware',
            name='specific',
            field=models.CharField(default=1, max_length=20, verbose_name='规格族'),
            preserve_default=False,
        ),
    ]
