# Generated by Django 2.0 on 2018-01-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_hosthardware_specific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosthardware',
            name='cpu',
            field=models.PositiveIntegerField(verbose_name='处理器'),
        ),
        migrations.AlterField(
            model_name='hosthardware',
            name='memory',
            field=models.PositiveIntegerField(verbose_name='内存'),
        ),
    ]
