# Generated by Django 2.0 on 2018-01-16 03:33

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_auto_20180115_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='到期时间'),
        ),
        migrations.AddField(
            model_name='host',
            name='pay_method',
            field=models.CharField(choices=[('reserved', '包年包月'), ('on_demand', '按量付费')], default='reserved', max_length=10, verbose_name='付费方式'),
        ),
        migrations.AddField(
            model_name='host',
            name='price',
            field=models.FloatField(default=10000.0, verbose_name='年费'),
        ),
        migrations.AlterField(
            model_name='hosthardware',
            name='cpu',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='最小为1')], verbose_name='处理器'),
        ),
        migrations.AlterField(
            model_name='hosthardware',
            name='memory',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='最小为1')], verbose_name='内存'),
        ),
    ]
