# Generated by Django 2.0 on 2018-01-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_auto_20180116_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='price',
        ),
    ]
