# Generated by Django 2.0 on 2018-01-16 03:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_remove_host_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000'), max_digits=2, verbose_name='年费'),
        ),
    ]
