# Generated by Django 2.0 on 2018-01-16 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_auto_20180116_1145'),
        ('server', '0024_host_price'),
    ]

    operations = [
    ]
