# Generated by Django 2.0 on 2018-01-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0029_auto_20180116_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='price',
        ),
    ]
