# Generated by Django 2.0 on 2018-02-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0033_auto_20180116_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('stopped', '已停止')], default='running', max_length=10, verbose_name='运行状态'),
        ),
    ]
