# Generated by Django 2.0 on 2018-03-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('admin', '0003_auto_20180313_1157'),
        ('users', '0003_auto_20180313_1157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='User',
        ),
    ]
